--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xqwtxon/Logger
build-by-default: true
branches:
- stable
projects:
  ExamplePlugin-CustomLogger:
    path: example/CustomLogger/
    libs:
      - src: xqwtxon\Logger
        version: ^0.0.1
  ExamplePlugin-Logger:
    path: example/ExamplePlugin/
    libs:
      - src: xqwtxon\Logger
        version: ^0.0.1
  Logger:
    path: ""
    model: virion
    type: library
...
