--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xqwtxon/Logger
build-by-default: true
branches:
- stable
projects:
  ExamplePlugin-CustomLogger:
    path: example/CustomLogger/
  ExamplePlugin-Logger:
    path: example/ExamplePlugin/
  Logger:
    path: ""
    model: virion
    type: library
...
