name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  phpstan:
    name: PHPStan analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.1.8"

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: pmmp/setup-php-action@main
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install PHPStan Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze
